# Generated by Django 4.0.1 on 2022-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('hour', models.IntegerField()),
                ('minute', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('interest', models.CharField(max_length=120)),
                ('selected', models.CharField(max_length=50)),
            ],
        ),
    ]
